# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Release on Tag

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: "1.20"

    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: go build -o justmysocks_exporter-${{ matrix.goos }}-${{ matrix.goarch }}

    - name: Get tag name
      id: get_tag_name
      run: echo "::set-output name=tag_name::${GITHUB_REF#refs/tags/}"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: justmysocks_exporter-${{ matrix.goos }}-${{ matrix.goarch }}.
        tag_name: ${{ steps.get_tag_name.outputs.tag_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
